name: Sanity Check

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version (e.g. 24.05)'
        required: true
        type: string

jobs:
  run-sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r tools/sanity-check/requirements.txt
      - name: Run sanity-check
        run: |
          source venv/bin/activate
          python tools/sanity-check/check.py CHANGELOG.md ${{ github.event.inputs.release }}

